---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
data:
  mongodb-root-password: cGFzc3dvcmQxMjM=
  mongodb-password: c2VjcmV0cGFzc3dvcmQxMjM=
  mongodb-replica-set-key: cmVwbGljYWtleQ==
