---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  type: LoadBalancer
  #type: ClusterIP
  #clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: mongodb
    port: 27017
    targetPort: mongodb
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: mongodb
