---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-metrics
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "9"
  labels:
    app.kubernetes.io/name: mongodb
spec:
  type: ClusterIP
  ports:
  - port: 9216
    targetPort: metrics
    protocol: TCP
    name: http-metrics
  selector:
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/component: mongodb
