---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    team: devops-by-example
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  endpoints:
  - honorLabels: true
    port: web
  selector:
    matchLabels:
      operated-prometheus: "true"
